name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar dependencias del Backend
        run: |
          source ~/.nvm/nvm.sh
          cd backend
          npm install

      - name: Inyectar variables de entorno Frontend
        run: cp ~/frontend.env ./frontend/.env.production || true

      - name: Instalar y construir Frontend
        run: |
          source ~/.nvm/nvm.sh
          cd frontend
          npm install
          npm run build

      - name: Inyectar variables de entorno Backend
        run: cp ~/backend.env ./backend/.env || true

      - name: Limpiar PM2 y liberar puerto 80
        run: |
          source ~/.nvm/nvm.sh
          pm2 delete api-frontend || true

      - name: Reiniciar Backend (Sirviendo el Frontend unificado) con PM2
        run: |
          source ~/.nvm/nvm.sh
          cd backend
          PORT=80 setsid pm2 restart api-backend --update-env || PORT=80 setsid pm2 start $GITHUB_WORKSPACE/backend/src/index.js --name "api-backend"
          pm2 save
    